### ISSUE TITLE
Population Data To-do List

### ISSUE THREAD

**Issue by tsitu** [tsitu/MH-Tools#79]
Consolidated list of population data that is missing or in need of update.

- [ ] Glowing Gourd Charms in Labyrinth/Zokor (ref: issue #14)
- [ ] Battering Ram Mouse (ref: issue #26)
- [ ] Living Garden SB+ (ref: issue #41)
- [ ] Moussu Picchu Wind/Rain (ref: issue #60)
- [ ] Warpath Commander Charm (ref: issue #63)
- [ ] Whisker Woods Rift (ref: forum [#88](https://www.mousehuntgame.com/forum/showthread.php?132397-MouseHunt-Tools-by-tsitu&p=1396994&viewfull=1#post1396994))
- [ ] Magical Rancid Radioactive Blue (ref: forum [#109](https://www.mousehuntgame.com/forum/showthread.php?132397-MouseHunt-Tools-by-tsitu&p=1403401&viewfull=1#post1403401))
- [ ] Claw Shot City / Prospector Charm (ref: forum [#111](https://www.mousehuntgame.com/forum/showthread.php?132397-MouseHunt-Tools-by-tsitu&p=1403974&viewfull=1#post1403974))
- [ ] Harbour / Pirate Bounty (ref: forum [#118](https://www.mousehuntgame.com/forum/showthread.php?132397-MouseHunt-Tools-by-tsitu&p=1405266&viewfull=1#post1405266), jack [#67](https://github.com/DevJackSmith/mh-hunt-helper/issues/67))

**Comment by tsitu** [comment]
Notes from my look into Glowing Gruyere's effect on potion farming pops:

```
{
  // Glowing Gruyere through all Wind/Rain stages
  cheese: utils.genVarField("cheese", ["Glowing Gruyere"]),
  phases: utils.genVarField("stage", stages)
}

time node data/tools/pop moussu-picchu
requesting {"cheese":{"Glowing Gruyere":true},"stage":{"Rain low":true},"location":{"Moussu Picchu":true}}
requesting {"cheese":{"Glowing Gruyere":true},"stage":{"Rain medium":true},"location":{"Moussu Picchu":true}}
requesting {"cheese":{"Glowing Gruyere":true},"stage":{"Rain high":true},"location":{"Moussu Picchu":true}}
requesting {"cheese":{"Glowing Gruyere":true},"stage":{"Rain max":true},"location":{"Moussu Picchu":true}}
requesting {"cheese":{"Glowing Gruyere":true},"stage":{"Wind low":true},"location":{"Moussu Picchu":true}}
requesting {"cheese":{"Glowing Gruyere":true},"stage":{"Wind medium":true},"location":{"Moussu Picchu":true}}
requesting {"cheese":{"Glowing Gruyere":true},"stage":{"Wind high":true},"location":{"Moussu Picchu":true}}
requesting {"cheese":{"Glowing Gruyere":true},"stage":{"Wind max":true},"location":{"Moussu Picchu":true}}

"Location","Phase","Cheese","Charm","Attraction Rate","Mouse","Sample Size"
"Moussu Picchu","Rain low","Glowing Gruyere","-","31.94%","Rainwater Purifier",839
"Moussu Picchu","Rain low","Glowing Gruyere","-","27.77%","Breeze Borrower",839
"Moussu Picchu","Rain low","Glowing Gruyere","-","18.00%","Windy Farmer",839
"Moussu Picchu","Rain low","Glowing Gruyere","-","14.54%","Cloud Collector",839
"Moussu Picchu","Rain low","Glowing Gruyere","-","7.75%","Homeopathic Apothecary",839
"Moussu Picchu","Rain medium","Glowing Gruyere","-","29.67%","Cloud Collector",1729
"Moussu Picchu","Rain medium","Glowing Gruyere","-","22.44%","Rainwater Purifier",1729
"Moussu Picchu","Rain medium","Glowing Gruyere","-","21.80%","Windy Farmer",1729
"Moussu Picchu","Rain medium","Glowing Gruyere","-","19.84%","Breeze Borrower",1729
"Moussu Picchu","Rain medium","Glowing Gruyere","-","6.25%","Homeopathic Apothecary",1729
"Moussu Picchu","Rain high","Glowing Gruyere","-","33.97%","Cloud Collector",730
"Moussu Picchu","Rain high","Glowing Gruyere","-","26.85%","Windy Farmer",730
"Moussu Picchu","Rain high","Glowing Gruyere","-","16.99%","Breeze Borrower",730
"Moussu Picchu","Rain high","Glowing Gruyere","-","16.44%","Rainwater Purifier",730
"Moussu Picchu","Rain high","Glowing Gruyere","-","5.75%","Homeopathic Apothecary",730
"Moussu Picchu","Rain max","Glowing Gruyere","-","38.24%","Cloud Collector",510
"Moussu Picchu","Rain max","Glowing Gruyere","-","36.86%","Windy Farmer",510
"Moussu Picchu","Rain max","Glowing Gruyere","-","10.78%","Rainwater Purifier",510
"Moussu Picchu","Rain max","Glowing Gruyere","-","10.00%","Breeze Borrower",510
"Moussu Picchu","Rain max","Glowing Gruyere","-","4.12%","Homeopathic Apothecary",510
"Moussu Picchu","Wind low","Glowing Gruyere","-","31.70%","Rainwater Purifier",877
"Moussu Picchu","Wind low","Glowing Gruyere","-","28.85%","Breeze Borrower",877
"Moussu Picchu","Wind low","Glowing Gruyere","-","16.08%","Cloud Collector",877
"Moussu Picchu","Wind low","Glowing Gruyere","-","15.28%","Windy Farmer",877
"Moussu Picchu","Wind low","Glowing Gruyere","-","8.10%","Homeopathic Apothecary",877
"Moussu Picchu","Wind medium","Glowing Gruyere","-","25.91%","Cloud Collector",1617
"Moussu Picchu","Wind medium","Glowing Gruyere","-","25.73%","Windy Farmer",1617
"Moussu Picchu","Wind medium","Glowing Gruyere","-","21.58%","Rainwater Purifier",1617
"Moussu Picchu","Wind medium","Glowing Gruyere","-","19.67%","Breeze Borrower",1617
"Moussu Picchu","Wind medium","Glowing Gruyere","-","7.11%","Homeopathic Apothecary",1617
"Moussu Picchu","Wind high","Glowing Gruyere","-","35.78%","Windy Farmer",763
"Moussu Picchu","Wind high","Glowing Gruyere","-","26.08%","Cloud Collector",763
"Moussu Picchu","Wind high","Glowing Gruyere","-","16.78%","Rainwater Purifier",763
"Moussu Picchu","Wind high","Glowing Gruyere","-","15.73%","Breeze Borrower",763
"Moussu Picchu","Wind high","Glowing Gruyere","-","5.64%","Homeopathic Apothecary",763
"Moussu Picchu","Wind max","Glowing Gruyere","-","38.71%","Windy Farmer",496
"Moussu Picchu","Wind max","Glowing Gruyere","-","35.89%","Cloud Collector",496
"Moussu Picchu","Wind max","Glowing Gruyere","-","10.89%","Rainwater Purifier",496
"Moussu Picchu","Wind max","Glowing Gruyere","-","10.08%","Breeze Borrower",496
"Moussu Picchu","Wind max","Glowing Gruyere","-","4.44%","Homeopathic Apothecary",496

real    5m4.459s
user    0m0.000s
sys     0m0.031s
```
